services:
  mysql:
    image: mysql:8.0
    container_name: hombre_maquina_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hombre_maquina
      MYSQL_USER: app
      MYSQL_PASSWORD: app123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
